apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nxiq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nxiq
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-nxiq
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nxiq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nxiq
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:87f80c88cd1278748ef56efbce78c5d4c32a1e714a39129d41e5c7d904c8c2f3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
